name: Sample Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission to Gradle wrapper
      working-directory: DhakaMetroRail/app/src/test/java/com/example/dhaka_metro_rail
      run: chmod +x ./gradlew
    - name: Run Gradle Tests
      working-directory: DhakaMetroRail/app/src/test/java/com/example/dhaka_metro_rail
      run: ./gradlew build
