name: Sample Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout code
       uses: actions/checkout@v4.1.1

     - name: Setup Java JDK
       uses: actions/setup-java@v4.0.0
       with:
          java-version: '17'
          distribution: 'adopt'
  
     - name: Build Gradle
       working-directory: DhakaMetroRail
       run: ./gradlew build

     - name: upload build artifact
       uses: actions/upload-artifact@v4.3.1
       with:
          name: DhakaMetroRail.apk
          path: app/build/outputs/apk/app-debug.apk
