name: Auto Merge Login Branch

on:
  push:
    branches:
      - SearchFriend

jobs:
  merge_searchfriend_branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge Search Friend branch into main
        run: |
          git config user.name "sakil"
          git config user.email "sakil390.28@gmail.com"
          git checkout main
          git merge --no-ff SearchFriend
          git push origin main
